version: '3.1'
services:
  stats-server:
    build: ./stat/stat-serv
    image: explore-with-me/stats-server
    restart: always
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USER=docker
      - SPRING_DATASOURCE_PASSWORD=docker

  stats-db:
    image: postgres:14-alpine
    restart: always
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=stats

  ewm-service:
    build: ./main
    image: explore-with-me/ewm-service
    restart: always
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USER=docker
      - SPRING_DATASOURCE_PASSWORD=docker

  ewm-db:
    image: postgres:14-alpine
    restart: always
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ewm